# This is the global config file for this site. All variables set here
# are available throughout the site via the "site" object, for example,
# {{ site.baseurl }}, {{ site.contributors.shortname.email }}, and so on.

# Note that if you are running a local Jekyll server (bundle exec jekyll serve),
# this file will not be reloaded when it is edited--you must restart the server.

title: "MUsic Technology Online Repository : Template"

email: your-email@example.com

description: ""

url: https://mutor-2.github.io

baseurl: /Template 

# add the names of the contributors to the website here.
# this is for people who actively work on the website, not for authors of units.
# email is optional
# color will be used to color the text of editorial notes (see example-unit.md)
contributors:
 shortname:
  fullname: First Last
  email: first.last@hfmt-hamburg.de
  color: "#0000FF"

# set this to true or false in order to display or
# hide editorial comments in the text
notes: true

# affiliate information used to create the footer.
# these will be processed in order, the top one being placed on the left
affiliates:
 hoou:
  url: "https://www.hoou.de/institutions/hochschule-fur-musik-und-theater"
  logo: "assets/images/hoou_logo.png"
  width: "auto"
  height: "48px"
  style: ""
 hfmt:
  url: "https://www.hfmt-hamburg.de/start/"
  logo: "assets/images/hfmt_logo_black.png"
  width: "auto"
  height: "80px"
  style: ""

# add the names of any files you want to appear in the menu.
# the value "units" is a keyword that will cause the units
# submenu to appear in the menu. 
menu:
 - units
 - references.md
 - discussion_questions.md
 - about.md
 - team.md

# these files will be excluded from processing
exclude:
 - _units/*/_*

# add other collections
collections:
 units:
  output: true

# do not change this.
markdown: kramdown